use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with parcel to recompile .js and .css sources.
config :dankchat, DankchatWeb.Endpoint,
  secret_key_base:
    "fYDaaOcH5ZEMJZ67MM/iTdv/8sUKEWs8LnpOO8/Fdq7O3uxBxXepuH3KOBXUH9z0",
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/.bin/parcel",
      "watch",
      "assets/js/app.js",
      "--out-dir",
      "./priv/static/assets",
      "--public-url",
      "/assets"
    ]
  ]

config :dankchat, Dankchat.Auth.Guardian, secret_key: "anho"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :dankchat, DankchatWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/dankchat_web/views/.*(ex)$},
      ~r{lib/dankchat_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :dankchat, Dankchat.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: Map.fetch!(System.get_env(), "USER"),
  database: "dankchat_dev",
  hostname: "localhost",
  pool_size: 10
